### ISSUE TITLE
Error: You need either xclip or xsel for emoji-keyboard to work

### ISSUE THREAD

**Issue by ghost** [OzymandiasTheGreat/emoji-keyboard#18]
"You need either xclip or xsel for emoji-keyboard to work" error message is presented with emoji-keyboard 2.2.0 on Linux Mint 18.2. All dependencies listed in the README were installed correctly, and the previous release (2.1.0) didn't have this issue.

Was able to resolve the issue by installing one of the mentioned packages, but this should be taken care of as part of the dependencies during installation.

**Comment by OzymandiasTheGreat** [comment]
I kinda rushed with this release...
These aren't dependencies because they should only be used when Gtk clipboard fails (e.g. under KDE).
Instead they are currently used by default which will be fixed in the next release.
That's gonna take a bit tho, because I'm currently pressed for spare time. Apologies.

**Comment by skmkenn** [comment]
No worries, thank you for the information.

**Comment by OzymandiasTheGreat** [comment]
Fixed in the latest release (2.3.0), correctly falling back on gtk clipboard now.
It's still better to have either xclip or xsel available, as gtk clipboard is rather buggy via python bindings at least.
