### ISSUE TITLE
On paste `CTRL-"keycode of v on english keyboards"` is pressed instead of always `CTRL-v`

### ISSUE THREAD

**Issue by raabf** [OzymandiasTheGreat/emoji-keyboard#19]
It seems to if emoji-keyboard is in `type` mode, on click it tries to paste an emoji through simutating pressing `CTRL`+`v`. However, instead it presses the key which is assigned through the keyboard layout to the key which is `v` on a standard default English keyboard.

#### Reproduce

 1. Select in your OS a keyboard layout where `v` is replaced by another key—for example for English people would be dvorak where `v` is replaced by `k`.
 2. If you now click on an emoji, `CTRL`+`k`and the respective function assigned to `CTRL`+`k` by the currently active window is executed and no emoji is inserted.

I did not found the code snippet in emoji-keyboard yet which is responsible for it. But currently I have to switch to a standard keyboard for pasting or use the `copy` mode—sadly both not optimal.

**Comment by OzymandiasTheGreat** [comment]
emoji-keyboard doesn't deal with keymaps at all, it's all done by python-evdev module.
It's seems they hard coded keycodes to keysyms which is a very bad idea, but there's nothing I can do about it short of implementing layout detection and doing the mapping myself, ~~which frankly would be a bigger project than emoji-keyboard itself~~. On second thought I might be able to get correct keycode from Gdk, which would be optimal since emoji-keyboard already depends on it. No guarantee that it correctly detects layout tho and layout changes during runtime wouldn't be detected at all iirc.
The relevant code starts at [line 212 in emoji_lib module.](https://github.com/OzymandiasTheGreat/emoji-keyboard/blob/83219ef8743358fc0fa846558220550605d2a8ca/lib/emoji_lib.py#L212)

**Comment by OzymandiasTheGreat** [comment]
Fixed in the latest release (2.3.0), using Gdk to get the correct keycode.
Note if you have both qwerty and dvorak layouts configured, `emoji-keyboard` will only work on the primary layout.
