### ISSUE TITLE
Cannot select emoji type

### ISSUE THREAD

**Issue by mpsijm** [OzymandiasTheGreat/emoji-keyboard#52]
When I want to switch from "blobmoji" to something else, the selector only shows "none". Same goes for the skin tone selector.

Using `emoji-keyboard-3.0.0-rc0.AppImage` on XUbuntu 19.10

![image](https://user-images.githubusercontent.com/9739541/74594328-666b0580-5035-11ea-9217-42255490233b.png)

**Comment by OzymandiasTheGreat** [comment]
Confirmed. Looking into it.

**Comment by OzymandiasTheGreat** [comment]
So. This is actually 2 issues. The first one is image paths invalidated by packaging. That's why skin tone selector shows lots of None's. This is fixed in `3.0.0rc1`.

The second issue and much more interesting is that when you click on select, it opens the select below. Will see what I can do about this later.

**Comment by mpsijm** [comment]
All right, thanks! :smile: At least I can switch types now, even though I have to mis-click :stuck_out_tongue:
