### ISSUE TITLE
AttributeError: 'TreeModelFilter' object has no attribute 'sort_new_with_model'

### ISSUE THREAD

**Issue by marimeireles** [OzymandiasTheGreat/emoji-keyboard#56]
Hello,

Getting this error when I run it on an Arch Linux with Python 3.8:

```
Traceback (most recent call last):
  File "/usr/bin/emoji-keyboard", line 22, in <module>
    shared.emoji = egtk.Emoji()
  File "/usr/lib/python3.8/site-packages/emoji_keyboard/emoji_gtk.py", line 126, in __init__
    self.categories = self.get_categories_filter()
  File "/usr/lib/python3.8/site-packages/emoji_keyboard/emoji_gtk.py", line 217, in get_categories_filter
    categories[category] = recent_filter.sort_new_with_model()
AttributeError: 'TreeModelFilter' object has no attribute 'sort_new_with_model'
```

**Comment by alechstong** [comment]
same error, running manjaro 19.02

**Comment by OzymandiasTheGreat** [comment]
Sorry for the late reply, been out with flu for almost 2 months now.
Anyway, this looks like another issue with Gtk bindings. There are a lot of these in Gtk, which is why I moved to electron.
Basically, not gonna fix. Try the new electron based version from releases page, that one has way fewer bugs by virtue of not using Gtk.
